dist: trusty
sudo: false
language: node_js
node_js: '8.10'
cache: yarn
before_install:
  - curl -sLo /tmp/terraform.zip https://releases.hashicorp.com/terraform/0.12.3/terraform_0.12.3_linux_amd64.zip
  - unzip /tmp/terraform.zip -d /tmp
  - mkdir ~/bin
  - mv /tmp/terraform ~/bin
  - export PATH="~/bin:$PATH"
install:
- yarn
jobs:
  include:
    - stage: lint
      script: yarn lint
    - stage: unit test
      script: yarn test:unit
    - stage: deploy
      deploy:
      - provider: script
        skip_cleanup: true
        script: terraform init ./terraform && terraform apply -var 'aws_access_key=$AWS_ACCESS_KEY' -var 'aws_secret_key=$AWS_SECRET_KEY' -var 'public_key_name=$PUBLIC_KEY_NAME' ./terraform
