dist: trusty
sudo: false
language: node_js
node_js: '8.10'
cache: yarn
before_install:
  - sudo apt-get install awscli -y
  - curl -sLo /tmp/terraform.zip https://releases.hashicorp.com/terraform/0.12.3/terraform_0.12.3_linux_amd64.zip
  - unzip /tmp/terraform.zip -d /tmp
  - mv /tmp/terraform ~/bin
  - export PATH="~/bin:$PATH"
install:
- yarn
jobs:
  include:
    - stage: lint
      script: yarn lint
    - stage: unit test
      script: yarn test:unit
    - stage: deploy
      deploy:
      - provider: script
        skip_cleanup: true
        script: cd ./.terraform &&
          terraform init -backend-config "bucket=heligram-deployment-state-bucket-$STAGE" -backend-config "lock_table=heligram-lock-state-table-$STAGE" -backend-config "key=terraform.tfState.$STAGE" -backend-config "region=$AWS_DEPLOYMENT_REGION" &&
          terraform apply -var 'public_key_name=$PUBLIC_KEY_NAME' -var 'aws_region=$AWS_DEPLOYMENT_REGION' -var 'stage=$STAGE'
        on:
          all_branches: true
