version: '3.1'

services:
  database:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
  app:
    image: node:8.16.0-jessie
    volumes:
      - ./:/usr/src/app
    command: bash -c "npm install -g yarn && cd /usr/src/app && yarn start"
    restart: always
    links:
      - database:database
    ports:
      - "3000:3000"
  web:
    image: nginx
    volumes:
      - .Docker/web.conf:/etc/nginx/conf.d/web.conf
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=heligram.com
      - NGINX_PORT=80
    links:
      - app:app
    command: /bin/bash -c "envsubst &lt; /etc/nginx/conf.d/web.conf &gt; /etc/nginx/conf.d/default.conf &amp;&amp; exec nginx -g 'daemon off;'"
