version: '3.1'

services:
  database:
    image: mongo:latest
    container_name: database
    restart: always
    ports:
      - "27017:27017"
  app:
    image: node:8.16.0-jessie
    container_name: app
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules/ # make node_module empty in container
    command: bash -c "npm install -g yarn && cd /usr/src/app && yarn && yarn start"
    restart: always
    links:
      - database:database
    ports:
      - "3000:3000"
  web:
    image: nginx
    container_name: web
    volumes:
      - .Docker/web.conf:/etc/nginx/nginx.conf
      - ./nginx/cache/:/etc/nginx/cache
    ports:
      - 80:80
    links:
      - app:app